---
title: "Bio"
author: "Samuel Montalvo, Ph.D., CSCS, *D"
date: 2020-12-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Welcome!

Hi and welcome to my personal website. My name is Dr. Samuel Montalvo, a research scientist, exercise and health advocate, and an athlete. As a research scientist, I am interested in understanding the mechanical, molecular, and physiological mechanisms to human performance. In addition, I am interesting in creating new and practical training methods to improve human exercise performance. 

Hola y bienvenido a mi sitio personal web. Mi nombre es Dr. Samuel Montalvo, investigador cientifico, promotor del ejercicio y salud, y atleta. Me encuentro interesado en estudiar y entender los mecanismos fisicos, fisologicos, mecanicos, y moleculares del ejercicio. Asi mismo, estoy interesado en crear nuevos metodos practicos de entrenamiento para mejor el rendimiento fisico durante el ejercicio.
